basePath: /api
definitions:
  handlers.RawTxRequest:
    properties:
      rawTxHex:
        example: 01000000...
        type: string
    required:
    - rawTxHex
    type: object
  handlers.TransferRequest:
    properties:
      request:
        items:
          properties:
            address:
              example: 1G6CB3Ch4zFkPmuhZzEyChQmrQPfi86qk3
              type: string
            amount:
              example: 0.1
              type: number
          required:
          - address
          - amount
          type: object
        type: array
      wifs:
        example:
        - L1dRKo...
        - K2...
        items:
          type: string
        type: array
    required:
    - request
    - wifs
    type: object
  models.GenericFailureResponse:
    properties:
      message:
        example: error description
        type: string
      success:
        example: false
        type: boolean
    type: object
  models.GetBalanceSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/types.BalanceDataDTO'
      message:
        type: string
      success:
        type: boolean
    type: object
  models.GetBalancesSuccessResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/types.BalanceDataDTO'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  models.GetConfigSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/types.SystemConfig'
      message:
        type: string
      success:
        type: boolean
    type: object
  models.GetHistorySuccessResponse:
    properties:
      data:
        $ref: '#/definitions/models.HistoryDataWrapper'
      success:
        example: true
        type: boolean
    type: object
  models.GetTicketSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/types.Ticket'
      success:
        example: true
        type: boolean
    type: object
  models.GetUtxosSuccessResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/types.MneeTxo'
        type: array
      success:
        example: true
        type: boolean
    type: object
  models.HistoryDataWrapper:
    properties:
      history:
        items:
          $ref: '#/definitions/types.TransactionHistoryDTO'
        type: array
    type: object
  models.PartialSignSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/models.RawTxWrapper'
      success:
        example: true
        type: boolean
    type: object
  models.RawTxWrapper:
    properties:
      rawTxHex:
        example: 02000000...
        type: string
    type: object
  models.TicketIdWrapper:
    properties:
      ticketId:
        example: KKJS-...
        type: string
    type: object
  models.TransferAsyncSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/models.TicketIdWrapper'
      success:
        example: true
        type: boolean
    type: object
  models.TransferSyncSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/types.TransferResponseDTO'
      success:
        example: true
        type: boolean
    type: object
  types.BalanceDataDTO:
    properties:
      address:
        type: string
      amt:
        type: number
      precised:
        type: number
    type: object
  types.BsvData:
    properties:
      amt:
        type: integer
      dec:
        type: integer
      icon:
        type: string
      id:
        type: string
      op:
        type: string
      sym:
        type: string
    type: object
  types.CosignData:
    properties:
      address:
        type: string
      cosigner:
        type: string
    type: object
  types.Data:
    properties:
      bsv21:
        $ref: '#/definitions/types.BsvData'
      cosign:
        $ref: '#/definitions/types.CosignData'
    type: object
  types.Fee:
    properties:
      fee:
        type: integer
      max:
        type: integer
      min:
        type: integer
    type: object
  types.MneeTxo:
    properties:
      data:
        $ref: '#/definitions/types.Data'
      height:
        type: integer
      idx:
        type: integer
      outpoint:
        type: string
      owners:
        items:
          type: string
        type: array
      satoshis:
        type: integer
      score:
        type: integer
      script:
        type: string
      senders:
        items:
          type: string
        type: array
      txid:
        type: string
      vout:
        type: integer
    type: object
  types.SystemConfig:
    properties:
      approver:
        type: string
      burnAddress:
        type: string
      decimals:
        type: integer
      feeAddress:
        type: string
      fees:
        items:
          $ref: '#/definitions/types.Fee'
        type: array
      mintAddress:
        type: string
      tokenId:
        type: string
    type: object
  types.Ticket:
    properties:
      action_requested:
        type: string
      callback_secret:
        type: string
      callback_url:
        type: string
      createdAt:
        type: string
      errors:
        items:
          type: string
        type: array
      id:
        type: string
      status:
        $ref: '#/definitions/types.TicketStatus'
      tx_hex:
        type: string
      tx_id:
        type: string
      updatedAt:
        type: string
    type: object
  types.TicketStatus:
    enum:
    - BROADCASTING
    - SUCCESS
    type: string
    x-enum-varnames:
    - BROADCASTING
    - SUCCESS
  types.TransactionHistoryDTO:
    properties:
      height:
        type: integer
      idx:
        type: integer
      outs:
        items:
          type: integer
        type: array
      rawtx:
        type: string
      receivers:
        items:
          type: string
        type: array
      score:
        type: integer
      senders:
        items:
          type: string
        type: array
      txid:
        type: string
    type: object
  types.TransferResponseDTO:
    properties:
      txhex:
        type: string
      txid:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A high-performance Golang REST API wrapper for the MNEE Golang SDK.
  title: MNEE SDK API Wrapper (Go)
  version: "1.1"
paths:
  /balance:
    get:
      description: Retrieves balances for a comma-separated list of addresses
      parameters:
      - description: Comma-separated list of addresses
        in: query
        name: addresses
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetBalancesSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Get balances for multiple addresses
      tags:
      - Balance
  /balance/{address}:
    get:
      description: Retrieves the MNEE balance for a specific wallet address
      parameters:
      - description: Wallet Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetBalanceSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Get balance for a single address
      tags:
      - Balance
  /config:
    get:
      description: Returns current MNEE system configuration.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetConfigSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Get System Config
      tags:
      - Config
  /transaction:
    get:
      description: Retrieves transaction history for one or more addresses with pagination
      parameters:
      - description: Comma-separated list of Wallet Addresses
        in: query
        name: addresses
        required: true
        type: string
      - description: Starting score (default 0)
        in: query
        name: fromScore
        type: integer
      - description: Limit (default 10)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetHistorySuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Get transaction history for multiple addresses
      tags:
      - History
  /transaction/partial-sign:
    post:
      consumes:
      - application/json
      description: Builds and signs a transaction *only* with the provided WIFs. Returns
        hex.
      parameters:
      - description: Transfer Parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PartialSignSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Partial Sign Transaction
      tags:
      - Transaction
  /transaction/status/{ticketId}:
    get:
      description: Polls the status of a transaction ticket until it is processed
        or times out.
      parameters:
      - description: Ticket ID
        in: path
        name: ticketId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetTicketSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Poll Ticket Status
      tags:
      - Transaction
  /transaction/submit-rawtx:
    post:
      consumes:
      - application/json
      description: Submits a pre-signed raw transaction hex and waits for the cosigner.
        Returns the final TxID.
      parameters:
      - description: Raw Hex
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RawTxRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransferSyncSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Submit Raw Transaction (Synchronous)
      tags:
      - Transfer
  /transaction/submit-rawtx-async:
    post:
      consumes:
      - application/json
      description: Submits a pre-signed raw transaction hex and returns a ticket ID
        immediately.
      parameters:
      - description: Raw Hex
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RawTxRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransferAsyncSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Submit Raw Transaction (Asynchronous)
      tags:
      - Transfer
  /transaction/transfer:
    post:
      consumes:
      - application/json
      description: Executes a transfer using multiple WIFs and waits for cosigner
        response. Returns final TxID.
      parameters:
      - description: Transfer Parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransferSyncSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Synchronous Transfer
      tags:
      - Transfer
  /transaction/transfer-async:
    post:
      consumes:
      - application/json
      description: Executes a transfer using multiple WIFs and returns a ticket ID
        immediately for polling.
      parameters:
      - description: Transfer Parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransferAsyncSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Asynchronous Transfer
      tags:
      - Transfer
  /utxos/all:
    get:
      description: Retrieves all unspent transaction outputs for one or more addresses
      parameters:
      - description: Comma-separated list of Wallet Addresses
        in: query
        name: addresses
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetUtxosSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Get all UTXOs for multiple addresses
      tags:
      - UTXO
  /utxos/paginated:
    get:
      description: Retrieves paginated unspent transaction outputs for one or more
        addresses
      parameters:
      - description: Comma-separated list of Wallet Addresses
        in: query
        name: addresses
        required: true
        type: string
      - description: Page number (default 1)
        in: query
        name: page
        type: integer
      - description: Page size (default 10)
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetUtxosSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.GenericFailureResponse'
      summary: Get paginated UTXOs for multiple addresses
      tags:
      - UTXO
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
